server.port=8080
#Data source 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Url donde esta el servicio de tu mysql y el nombre de la base de datos
spring.datasource.url=jdbc:postgresql://ep-ancient-forest-34242953.us-east-2.aws.neon.tech/anunciadb?sslmode=require

#Usuario y contrasena 
spring.datasource.username=fl0user
spring.datasource.password=9BrPWVIDk8YJ

spring.jpa.show-sql = true

token = 1f9d97c52fb351d56a1bc7ffe1140e58
